### ISSUE TITLE
Collapse in code?

### ISSUE THREAD

**Issue by jaarong** [arielfaur/ionic-pullup#11]
Sorry if this is a simpleton question, but I'm trying to collapse the bar after the user hits a button within the content of the pull-up bar.  Is there a way to do that cleanly within my function?

**Comment by bianchimro** [comment]
Hi, great component!

Same need here: I'd need to collapse the component when clicking a button insidie `ion-pull-up-content`.
In my case the pullup contains a search form and the button should set the filter and close the pullup.

My ideas:

* introduce a service like "$ionicPullUpDelegate", behaving lilke $ionicScollDelegate
* listen to some $broadcast to close the pullup from outside (in fact, there should be only one pullup in the view normally)

**Comment by arielfaur** [comment]
Hi there! Thanks for your feedback. I have implemented a way to change the footer state by means of a new directive attribute that takes an expression which must resolve to the expected state:

````
<ion-pull-up-footer class="bar-energized" on-expand="onFooterExpand()" on-collapse="onFooterCollapse()" state="footerState">
...
</ion-pull-up-footer>
```
Then in your controller simply bind ```footerState```. You can inject ```ionPullUpFooterState``` to have access to the footer state constants:
````
.controller('DashCtrl', function($scope, $timeout, ionPullUpFooterState) {
      $scope.onFooterExpand = function() {
        console.log('Footer expanded');
      };
      $scope.onFooterCollapse = function() {
          console.log('Footer collapsed');
      };

      $scope.expand = function() {
        $scope.footerState = ionPullUpFooterState.EXPANDED;  
      };
  })
````

Let me know if that works well for you.

**Comment by bianchimro** [comment]
hi @arielfaur, 
thanks for the quick response!

This is great, 
just tested and it works perfectly for me.

best regards

**Comment by ffabreti** [comment]
Thank you.
I have setup a codepen to ilustrate the new state attr:
http://codepen.io/ffabreti/pen/qbLNRM

**Comment by MichaelApproved** [comment]
One use-case that's not covered is expanding twice in a row. 

If a customer clicks expand and then manually drags to be smaller, the state will stay as expanded. That means, when you click expand again, the state won't change and the expand action won't fire.

To get around this behavior, you can set the state to an empty string and then have a fast timeout object set the state to expand. This way, it'll always trigger the state change action and expand the footer.

```javascript
$scope.footerState = '';
$timeout(function () {
	$scope.footerState = ionPullUpFooterState.EXPANDED;
}, 100);
```

(thanks for creating the plugin!)

**Comment by lync0056** [comment]
Hi All. Great feature to be able to use footerState. Any reason you can think why it might not work inside a model? Have it working perfectly elsewhere. 

Inside the model the directive 'ion-pull-up-trigger' on the ion-pullup-bar works fine. Have it going up and down. Just can't implement footerState on content elsewhere.

Cheers

**Comment by arielfaur** [comment]
@MichaelApproved Thanks for the hint!

@lync0056 what do you mean by inside a model?

**Comment by lync0056** [comment]
Sorry. Typo autocorrect. Modal. Not Model.

Sent from Outlook Mobile




On Wed, Apr 20, 2016 at 4:47 AM -0700, "arielfaur" <notifications@github.com> wrote:












@MichaelApproved Thanks for the hint!



@lync0056 what do you mean by inside a model?
