### ISSUE TITLE
Using ng-class: ion-pull-up-handle does not change class

### ISSUE THREAD

**Issue by bianchimro** [arielfaur/ionic-pullup#12]
Hi, great component!

I noticed an issue when using `ng-class` for setting the  class.

see this example:

http://codepen.io/bianchimro/pen/rxGjWr

if you click the button to toggle the class, the pull-handler won't follow the class change.

If you don't set an initial class on `ion-pull-up-footer` and use `ng-class` only, `ion-pull-up-handle` won't have any class set.

**Comment by arielfaur** [comment]
Yes, the handle inherits the initial bar style but it does not watch for changes. I have been playing around with your codepen but that change means a major refactor. Unfortunately I don't have time these days!

**Comment by bianchimro** [comment]
Hi,
maybe I found i quick solution, 
it sets 

`'background-color' : 'inherit',`

of `ionPullUpHandle` directive.

see this pen:

http://codepen.io/bianchimro/pen/qbPYgm

I'm going to open a PR, see if you are interested in merging it.

**Comment by arielfaur** [comment]
@bianchimro awesome!

**Comment by AdrienDC** [comment]
+1 ! nice finding @bianchimro

**Comment by bianchimro** [comment]
@AdrienDC I personally never used this css rule before this ;)

**Comment by AdrienDC** [comment]
same here ;P

**Comment by bianchimro** [comment]
I think we can close this, the use case I was using `ng-class` for is now covered by the fact that the `ion-pull-up-handle` background is inherited from its parent (`ion-pull-up-footer`) now.
