### ISSUE TITLE
Autoclose

### ISSUE THREAD

**Issue by chukwu** [arielfaur/ionic-pullup#16]
The documentation says nothing about close/collapse method. How can i collapse the panel based on an method call from my controller.

**Comment by arielfaur** [comment]
That is because this functionality is implemented in master branch but not yet built in the latest release. You can download the master branch and give it a try. Details here: #11

**Comment by chukwu** [comment]
can you share a code snippet to achieve this?

**Comment by arielfaur** [comment]
Have you looked at the link #11 ? There's a code snippet there and a link to a codepen example at the bottom.
