### ISSUE TITLE
Bottom position calculation messed up when directive used in different views

### ISSUE THREAD

**Issue by jsanta** [arielfaur/ionic-pullup#17]
Hi!
I have the following problem. My app has several different views where some have an additional header, and others don't.
Using the exact same code from the examples page, I'm getting different results. The ion-pull-up-footer bottom style is messed up depending on which page I visit first. Sometimes the footer get hidden far beyond sight, or gets a margin below the handle, or doesn't show the ion-pull-up-bar title when collapsed.

Is there any way of setting this value depending on the real height of the  ion-view as the base value (and then substracting the handle and title heights)?

Tried to edit the plugin myself but  I ended screwing everything even more :(
Hope you can help or give me an advice.

Best regards.

**Comment by arielfaur** [comment]
Is there any chance you can upload the project to codepen? The module should determine the correct height but it may be that not all use cases are covered. Do you have any subheaders? I believe subheaders are not implemented yet (so far only header, tabs and footer are provided for...)

**Comment by jsanta** [comment]
Sorry, cannot upload the code to codepen.
My pages do use subheaders, and just figured out what causes the problem. When you navigate in the app, nav-views are cached and included in the DOM. The .tab, .header and other lookups are  done considering the whole HTML, not just the active view, that seems to be the problem.

**Comment by arielfaur** [comment]
That makes sense because I am using ```document.querySelector``` to find out whether those elements are present. Thanks for the heads up! Unfortunately I am out of time at the moment but I will try to look into it in the next few days/weeks.

**Comment by jsanta** [comment]
Hi! Just checked out the new commits that suppose to fix this. 
It doesn't work, I  notice the same problem reported earlier. I'm trying to make a query that correctly calculates the correct top position. By hand the second parameter on translate3d in some cases has to be less than the footer's defined max-height.

Looking at the examples, is there any exception where the ion-footer is defined outside a ion-view or in other place than after the ion-content? I'm asking this because a way of getting the correct active view (to calculate heights and position corrections) is to query for the ion-footer in the active view, just after the ion-content.
IMHO it's not so terrible to restrict the position of the ion-footer to inside ion-view and after ion-content, so it works correctly. That should make all calculations easier.

I'll test some of my ideas.
Best regards.

**Comment by arielfaur** [comment]
Hi @jsanta 
Have you checked the builtin example? I updated it to have that use case: two different views, one with tabs and another on with just a header.  And I have also changed the query strategy, I am querying for the active view. I tested it on Chrome and Safari and works on my end.  Are you sure you pulled the latest version?

**Comment by jsanta** [comment]
Hi @arielfaur . I did the update the old way, took the new file directly from git and replaced the one I had on my project.
Maybe I'm seeing things a little too simple, the bottom offset (as I'm calling the value) should be calculated based on the ion-content (before ion-pullup) bottom position. 
A much simpler approach would be adding an offset parameter, no queries or calculations involved.

I'm doing some tests, I'll share my findings.

**Comment by arielfaur** [comment]
OK, just keep in mind that this update requires ionic 1.3 (and Angular 1.5) otherwise it won't work.
Let me know your thoughts later.

**Comment by jsanta** [comment]
Forgot to mention, also updated the Ionic and Angular versions so that's not an issue ;)
