### ISSUE TITLE
Restricting gestures

### ISSUE THREAD

**Issue by D0rx** [arielfaur/ionic-pullup#18]
Hello and thanks for a great plugin!

I've experienced that the pullup-bar some times goes too far down when using gestures, which makes it impossible to retrieve. Is there any way to reset the bar-placement? The view the bar resides in will almost never be refreshed, so I was hoping I could control this programatically, but so far I haven't found anything.

**Comment by arielfaur** [comment]
Hi @D0rx 
Are you adding the pullup-bar to different views or only one view? A user has reported similar issues #17

**Comment by D0rx** [comment]
Hi @arielfaur, I am adding this to one view only. I understand how I might be a bit vague with "resetting the bar placement" but what I'm trying to ask for is if it's possible to reset the bar to a collapsed state if that's the default state, minimized if that is default etc. as current behaviour in my app always keeps this bar opened between page-changes.

**Comment by arielfaur** [comment]
So whenever you expand/collapse the bar it goes beyond the view boundaries. Do you have any idea when that happens? Are there any other elements in the view besides a head or subheader?

If I understand correctly you expand the footer, switch views, then go back to original view and the footer remains in the same state you left it. You want to collapse it programmatically. Is that correct?
There's a way to control the bar from the controller. Please take a look at this thread #11 
I haven't built a release yet so you need to download the master branch to get the update.

**Comment by D0rx** [comment]
It doesn't necessarily go beyond the boundaries, but it goes too far down to be retrievable by either a toggle or a gesture. I guess it's worth mentioning that I don't use a handle for my bar. 

It looks like the link you sent will solve this for me though. I will have a look. Thanks!

**Comment by arielfaur** [comment]
Is the footer set to minimized state?

**Comment by D0rx** [comment]
No, it's set to collapsed.
