### ISSUE TITLE
new release on bower

### ISSUE THREAD

**Issue by bianchimro** [arielfaur/ionic-pullup#19]
Hi @arielfaur ,
it's a been a while since last release, and some interesting features has been added since then.
A new release would be cool so we can checkout the latest things directly from bower.

best regards

Mauro

**Comment by arielfaur** [comment]
Hi @bianchimro You mean the features in recent pull requests?

**Comment by bianchimro** [comment]
@arielfaur yes, I just noticed as I was using your plugin in a new project, and the checked out version was missing the last merged features. Not a big problem, but I think they are worth a new version tag (especially the `state` scope binding).

**Comment by arielfaur** [comment]
You're right, I totally forgot about the latest ```state``` scope parameter. Could you merge your pull requests? I will add you as collaborator, then I can create a new release with all your fixes.

**Comment by bianchimro** [comment]
That would be great.
There should be only one PR open from me now, try and check if you can merge it as I just noticed that I deleted my fork, but the PR is still there, so maybe it can still be merged.
If this does not work let me know, so that I can re-fork and make another PR.

**Comment by arielfaur** [comment]
I've seen you managed to merge. I will check it out later. Busy now :)

**Comment by arielfaur** [comment]
Also, it is already midnight in Italy... still working ? :)

**Comment by bianchimro** [comment]
:) ah ah ... I was just checking a mail before got to sleep (bad habit I know ...) but saw your msg, and sudden realized I made two PR for the same thing ... 
... but in the end yes ... too much work anyway ;)

**Comment by arielfaur** [comment]
Hi @bianchimro 

I have just pushed a new version to the master branch with a lot of changes. Could you please have a look at it when you have some time? I have included #21, #7 and #13 in this release. Also, I updated the module to work with Ionic 1.3 and Angular 1.5.  So this is a breaking change :)

**Comment by bianchimro** [comment]
hi @arielfaur, this is definitely good news, will try and take a look this week.
regards
Mauro

**Comment by bianchimro** [comment]
hi @arielfaur, just seen the release tag, 
sorry I didn't manage to take a look at this issue before.

The new code looks good to me, and I really appreciate your choice to require the latest ionic and angular (1.3 and 1.5 as of now), this is also a good way to prepare for 2.0. (Any plan on this?)

Thanks for this great release!
