### ISSUE TITLE
footerState not working inside a Modal

### ISSUE THREAD

**Issue by lync0056** [arielfaur/ionic-pullup#23]
The footerState is not working inside a Modal. Any idea how to get around this?

Inside the Modal, the directive 'ion-pull-up-trigger' on the ion-pullup-bar works fine. Have it going up and down. Just can't implement footerState on content elsewhere.
![screen shot 2016-04-24 at 8 52 48 pm](https://cloud.githubusercontent.com/assets/15604237/14767190/fcd6e686-0a5e-11e6-841e-7a64018c69b1.png)

Cheers

**Comment by arielfaur** [comment]
I have never tried that use case within a modal. Can you create a codepen with that code so we can test?

**Comment by lync0056** [comment]
Sorry to waste your time. It must be an issue in my private code because its working when I push it in a codepen

http://codepen.io/lync0056/pen/PNBgVb?editors=0010
