### ISSUE TITLE
IOS do not expand since last release

### ISSUE THREAD

**Issue by AdrienDC** [arielfaur/ionic-pullup#24]
HI team,
since the last release, I'm not able to expand the pullup on IOS only.
Here is my code:

`<ion-pull-up-footer class="bar-calm" on-expand="footerExpand()" on-collapse="footerCollapse()"
        on-minimize="footerCollapse()" initial-state="minimized" state="footerState" style="z-index:0">
        <ion-pull-up-handle width="100" height="25" icon-expand="ion-chevron-up" icon-collapse="ion-chevron-down" style="border-radius: 25px 25px 0 0">
            
            
        </ion-pull-up-handle>`

**Comment by arielfaur** [comment]
Hi @AdrienDC 

Have you upgraded your project to Ionic 1.3 ? Also, what iOS version are you running?

I am right now testing it on my iPhone with iOS 9.3 and it works like a charm.

**Comment by AdrienDC** [comment]
Hi Ariel,
in fact it's not directly on IOS but through Ionic View on IOS. Version 1.0.3 works perfectly but not 1.1.0

**Comment by arielfaur** [comment]
I never use Ionic View so I don't know much about it. Are you sure you are running the latest Ionic 1.3 ?

**Comment by AdrienDC** [comment]
Yes 100% sure ^^
Nevermind I revert back to 1.0.3, I'll try later on plain IOS.

**Comment by arielfaur** [comment]
Did you ever solve this?

**Comment by AdrienDC** [comment]
Hi Ariel, I haven't reupdated the lib yet but I'll keep you posted. I close it for now and reopen after in case.
