### ISSUE TITLE
Trigger it !

### ISSUE THREAD

**Issue by LeVadim** [arielfaur/ionic-pullup#26]
Hi! I have a situation like this, how to achieve it?

```
window.socket.on('new action',function(data){
   //// expand pull up
});
```

**Comment by arielfaur** [comment]
Hi @LeVadim 
Sorry I have updated the docs with the new parameters to control the footer with the API. Take a look [here] (http://arielfaur.github.io/ionic-pullup/). There is a section that explains how to control the footer with the API. It's quite simple, you only need to bind a variable.

**Comment by jdnichollsc** [comment]
Thanks my friend! See my example: http://codepen.io/jdnichollsc/pen/WxkAqg?editors=1010

**Comment by arielfaur** [comment]
:+1:
