### ISSUE TITLE
Any plan to make a ionic2-pullup?

### ISSUE THREAD

**Issue by tagazok** [arielfaur/ionic-pullup#27]
Hi,
Ionic2 is coming and I was wondering if you are working on a version of ionic-pullup for ionic2?

**Comment by arielfaur** [comment]
I have already started working on a plugin version for Ionic 2. There are a few challenges on the way that I am trying to solve. I hope to come up with a first version soon :smile:

**Comment by arielfaur** [comment]
@tagazok I have uploaded a first version of ionic2 pullup to a new branch: https://github.com/arielfaur/ionic-pullup/tree/2.0

Keep in mind this is a first release, there are still some minor issues to fix but the basic functionality to expand/collapse is there. Can you give it a try? Tested on web and Android 6 so far.
