### ISSUE TITLE
magnifying glass callout appears on iOS

### ISSUE THREAD

**Issue by pliablepixels** [arielfaur/ionic-pullup#3]
Hello, I am facing an issue where if you long press on any area in the pullup window (but not inside the list inside the content), a callout window appears.

Here is a screenshot

I tried adding 
```<div style="-webkit-user-select:none;-webkit-user-callout:none">```
around the pullup call, but that did not help either

![img_2329](https://cloud.githubusercontent.com/assets/4116654/9997160/a922af30-6058-11e5-817a-820e93e0a5f4.PNG)

**Comment by arielfaur** [comment]
Right! I see it now. I have no idea how to disable it. Any hints?

**Comment by pliablepixels** [comment]
Not yet. I've been trolling stackOverflow - it seems this is what is called a 'callout' that can be disabled by ```'-webkit-user-callout': 'none','-webkit-user-select':'none'``` but I haven't gotten it working yet

**Comment by pliablepixels** [comment]
I can confirm this is an IOS9 only bug. It's UIWebView is ignoring the CSS fix that should be disabling this callout. To fix this, your users can install this plugin which patches UIWebview to ignore long press detection https://github.com/EddyVerbruggen/cordova-plugin-ios-longpress-fix. Fortunately adding this fix does _not_ interfere with ionic's own long press detection, so it does not lose functionality
