### ISSUE TITLE
ionic-content is cut off by ion-navbar

### ISSUE THREAD

**Issue by Poeticode** [arielfaur/ionic-pullup#31]
I've placed <ion-pullup> after the <ion-content> in the example project's "item-details.html" page. This results in the text within <ion-content> being cut off by the ionic navbar. I've installed Crosswalk, and still encounter this issue.

If I take out the <ion-content> that's inside <ion-pullup>, the issue goes away, but then you can't add anything beyond the <ion-toolbar> and <ion-pullup-tab> within <ion-pullup>.

**Comment by arielfaur** [comment]
@Poeticode are you using ionic 1 or 2?

**Comment by divanvb** [comment]
Same here, mine is also cutting off with ionic 2

**Comment by arielfaur** [comment]
@Poeticode I cannot really understand what you wrote above. It seems that you text was also cut off. Where did you place the component exactly?
