### ISSUE TITLE
Can't import module

### ISSUE THREAD

**Issue by divanvb** [arielfaur/ionic-pullup#32]
Hi, I see you have the ionic-pullup folder in the app folder, but installed mine into node_modules and can't resolve path to import it into project. Any suggestions?

Thanks.

**Comment by arielfaur** [comment]
Nobody knows how to do this. I have been struggling with that too. That's why I have included the module code inside the app folder. Perhaps someone else knows how to deal with it.

**Comment by divanvb** [comment]
Ah okay, yeah I've been trying to figure it out for over 2 hours but also just ended up placing the folder inside the app folder. 

A few things, importing certain modules from the folder such as IonPullUpComponent & IonPullUpTabComponent inside the desired file, doesn't really do anything I've noticed. Only importing IonPullUpFooterState was necessary. Is it safe to do so or not?

**Comment by divanvb** [comment]
And is there away to remove the toolbar to only have the icon centered without any background color and simple text underneath the icon?

**Comment by arielfaur** [comment]
Yes, you can ignore the other imports if you are not using them. I am not sure what you are trying to achieve. What do you mean by removing the toolbar?

**Comment by divanvb** [comment]
The toolbar is currently the footer, now I want to basically remove the footer and only have the icon with a small bit of text underneath the icon, because currently the toolbar is overlapping some of my content on my page but without the toolbar I'm sure it will go away.  Now the problem is when I remove the toolbar from the HTML, it throws and error which im guessing its being used in the TS files.

**Comment by arielfaur** [comment]
There are two components: the footer and the tab (or handle) that contains the icon. If you remove the footer that will break everything. Actually then you wouldn't need this component at all if you don't need a footer in your page.

**Comment by divanvb** [comment]
It's not that I want to remove the footer, just replace the toolbar with a <p> for example and still it have a width of 100% to be able to click on to expand the footer but I'll try work with the toolbar and see if I can hack it a bit

**Comment by kabelo38** [comment]
if you look under node_modules/ionic-pullup/

there's a demo folder that contains example of how to implement pullup with ionic 2

**Comment by m-spyratos** [comment]
#34

**Comment by arielfaur** [comment]
Recently upgraded module to work with Ionic 2 final. Please take a look at the updated docs, the setup is easier now. 

http://arielfaur.github.io/ionic-pullup/
