### ISSUE TITLE
Footer content not scrolling

### ISSUE THREAD

**Issue by divanvb** [arielfaur/ionic-pullup#33]
Hey man, implemented it and everything but when I cant scroll the content inside the footer.

**Comment by arielfaur** [comment]
Hmmm, I tested on Android and it seemed to work fine. I will look into it whenever I find time.

**Comment by divanvb** [comment]
I know it's strange and I didn't change anything, built to phone(android) but still not scrolling and not even in the browser for some reason

**Comment by varepato** [comment]
I'm having the same issue and also the content in home.html not showing.

**Comment by arielfaur** [comment]
Can you check the new version I just uploaded? I upgraded the module to be compatible with Ionic 2 final.
Check the updated docs as the setup is different now.
http://arielfaur.github.io/ionic-pullup/
