### ISSUE TITLE
Drag event not working?

### ISSUE THREAD

**Issue by GeorgeRCole** [arielfaur/ionic-pullup#45]
Hi,

Can anyone confirm whether the drag event is working with this plugin? 

I'm using ionic-pullup for Ionic 2 and Angular 2. When I build the demo project for ionic-pullup and run it on an android phone I cannot drag the footer up - it only responds to the tap event.

The codepen demos clearly show the drag event working for an earlier version of this plugin:
http://arielfaur.github.io/ionic-pullup/index.v1.html

Many thanks,
George

**Comment by chenyuanchn** [comment]
@GeorgeRCole  I met the same problem. Have you solved it?

**Comment by GeorgeRCole** [comment]
I found a good work around by starting with Josh Morony's tutorial, which produces a pullup drawer with good swipe action. You can then add more functionality, e.g. using the ionic-pullup project for inspiration.  
https://www.joshmorony.com/how-to-create-a-sliding-drawer-component-for-ionic-2/

**Comment by arielfaur** [comment]
@GeorgeRCole Thanks for the link. I had seen that already. Unfortunately this seems quite complicated to implement with this plugin. I have been already been struggling to add drag and pan events. I hope I find a fix soon!
