### ISSUE TITLE
Not Stick to bottom

### ISSUE THREAD

**Issue by IshaqBhojaniGenetech** [arielfaur/ionic-pullup#46]
Hi there, I'm new in Ionic 3 & trying to use this repo in my project but it shows some gap from bottom, Please check screen Shots.

Nexus 5x:

![localhost_8100_ nexus 5x](https://user-images.githubusercontent.com/31653151/32592705-d2572f66-c546-11e7-9b9a-615459187313.png)

Iphone 6:

![localhost_8100_ iphone 6 2](https://user-images.githubusercontent.com/31653151/32592708-d393ea68-c546-11e7-8e5d-60f5cbf55bc1.png)

Am I doing something wrong or is this a bug, Any help would be appreciated. Thanks

**Comment by thiphariel** [comment]
Hello. I've the same issue here. This gap happen when you had the "padding" directive to the `ion-content` of the pullup.

Any chance to avoid that behaviour without redefining the padding ourselves ?
