### ISSUE TITLE
Solving the "flickering" problem while changing orientation

### ISSUE THREAD

**Issue by pliablepixels** [arielfaur/ionic-pullup#5]
@arielfaur, the reason that flickering is happening when we change orientation is that the "300ms ease-in out" transition is still in effect. The solution might be to make that transition "none" during orientation change and re-enable it on expand. I'll submit a PR with this code for you to look at. It works on my iOS and Android device and seems to eliminate the flickering problem

**Comment by arielfaur** [comment]
Thanks again!
