### ISSUE TITLE
Ionic 4 support

### ISSUE THREAD

**Issue by jhgeluk** [arielfaur/ionic-pullup#50]
Hi,

Will ionic 4 be supported in the future?

**Comment by arielfaur** [comment]
Hi @SaltyPotato I've just pushed a new beta version to NPM with Ionic 4 support. Also, I've updated this repo with the latest source code.

**Comment by SaltyPotato** [comment]
When will there be a fully stable release?

**Comment by arielfaur** [comment]
@SaltyPotato This beta version needs more testers. I've actually used in one project for one of my clients already in production and seems to work fine. Have you experienced any issues?
