### ISSUE TITLE
Unable to assign dynamic value to [toolbarTopMargin] property

### ISSUE THREAD

**Issue by AnkitS221** [arielfaur/ionic-pullup#54]
![Screenshot from 2020-10-21 15-28-28](https://user-images.githubusercontent.com/37686348/96704806-1dccce80-13b2-11eb-9f0a-ff006860fb6d.png)

Hello,
Receiving above error when trying to assign a dynamic value to a [toolbarTopMargin] property.
Code in question:
1.html
<lib-ionic-pullup (onExpand)="footerExpanded()" (onCollapse)="footerCollapsed()" [(state)]="footerState"
  [minBottomVisible]="minHeight" [toolbarTopMargin]="toolbarMargin">

1.ts
  ngAfterViewInit() {
    setTimeout(() => {
      const contentHeight = document.querySelector('app-payment-popup').clientHeight;
      this.width_ele = this.contentData.nativeElement.offsetHeight;
      if (this.width_ele) {
        this.toolbarMargin = contentHeight - this.width_ele;
        console.log(this.toolbarMargin);
      }
    }, 300);
  }

Can someone please explain above error and a quick solution to solve above issue.
New to ionic pullup
Thanks

**Comment by arielfaur** [comment]
Hi @AnkitS221,
What happens if you assign a constant to `toolbarMargin` in `ngAfterViewInit` ? 

Could you try something like 
```
ngAfterViewInit() { 
  this.toolbarMargin = 100
}
```

Is there still an error?

**Comment by AnkitS221** [comment]
> Hi @AnkitS221,
> What happens if you assign a constant to `toolbarMargin` in `ngAfterViewInit` ?
> 
> Could you try something like
> 
> ```
> ngAfterViewInit() { 
>   this.toolbarMargin = 100
> }
> ```
> 
> Is there still an error?

Hi @arielfaur ,
Apologies for late reply
Yes, I have tried this and the same issue seems to occur, without even assigning a calculated value

Thanks for your reply

**Comment by arielfaur** [comment]
Hmm, I'll look into it! Thanks!

**Comment by arielfaur** [comment]
Hi @AnkitS221 

I've just released an update that fixes this issue. Could you please check the latest release v5.0.0-beta.3? It's already on NPM.

Thanks,
Ariel

**Comment by AnkitS221** [comment]
Hi @arielfaur ,

I have tried the latest beta version and it's working fine

Thanks for your help
Great library
