### ISSUE TITLE
Feature Request - Pull Down?

### ISSUE THREAD

**Issue by kevincobain2000** [arielfaur/ionic-pullup#8]
I thought it'd be cool to have two together on a page, one  ionic-pullup like now and ionic-pulldown from the top to bottom. 
Any thoughts on doing such?

**Comment by arielfaur** [comment]
Hmmm... I am not sure if it's a good idea since the pull down gesture is used by the pull-to-refresh component in Ionic (http://ionicframework.com/docs/api/directive/ionRefresher)

**Comment by kevincobain2000** [comment]
makes sense. thanks
anyways I saw that you have a sidebar. I ll use that!!
https://github.com/arielfaur/ionic-sidetabs
