### ISSUE TITLE
Android 4.1.1 content display issue

### ISSUE THREAD

**Issue by AdrienDC** [arielfaur/ionic-pullup#9]
Hi,
somehow for Android 4.1.1, content is not showing except if a ion content is placed in the ion-pull-up content but the display is not really great...
Also at the bottom the the pull up is collapsed, only the arrow is shown, not the css component.

Thanks

**Comment by arielfaur** [comment]
Are you using Crosswalk in your project?

**Comment by AdrienDC** [comment]
Not yet because it's heavy for testing but I'll give a try, it should be better indeed.

**Comment by arielfaur** [comment]
Both the pull-up and sidetabs components require crosswalk on Android
versions below 4.4 (KitKat)

**Comment by AdrienDC** [comment]
A good workaround was to put a <ion-pane> in the pullup content

**Comment by AdrienDC** [comment]
Ah ok, Thanks for your help @arielfaur
